# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "rj_smtr"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

vars:
  data_inclusao_agency: "2021-08-03"
  data_inclusao_stop_times: "2021-08-03"
  data_inclusao_linhas: "2021-08-03"
  data_inclusao_routes: "2021-08-03"
  data_inclusao_trips: "2021-08-03"
  data_inclusao_shapes: "2021-08-24"
  data_inclusao_stops: "2021-08-24"
  data_inclusao_calendar: "2021-09-30"
  data_inclusao_frota_determinada: "2021-09-30"
  data_inclusao_stop_details: "2021-09-30"
  data_inclusao_holidays: "2021-11-05"

  agency: "rj-smtr.br_rj_riodejaneiro_sigmob.agency"
  calendar: "rj-smtr.br_rj_riodejaneiro_sigmob.calendar"
  frota_determinada: "rj-smtr.br_rj_riodejaneiro_sigmob.frota_determinada"
  holidays: "rj-smtr.br_rj_riodejaneiro_sigmob.holidays"
  linhas: "rj-smtr.br_rj_riodejaneiro_sigmob.linhas"
  routes: "rj-smtr.br_rj_riodejaneiro_sigmob.routes"
  shapes: "rj-smtr.br_rj_riodejaneiro_sigmob.shapes"
  shapes_geom: "rj-smtr.br_rj_riodejaneiro_sigmob.shapes_geom"
  stop_times: "rj-smtr.br_rj_riodejaneiro_sigmob.stop_times"
  stop_details: "rj-smtr.br_rj_riodejaneiro_sigmob.stop_details"
  stops: "rj-smtr.br_rj_riodejaneiro_sigmob.stops"
  trips: "rj-smtr.br_rj_riodejaneiro_sigmob.trips"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  rj_smtr:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view # Materialization type (view, table or incremental)
      +schema: example # Overrides the default schema (defaults to what is set on profiles.yml)
    br_rj_riodejaneiro_sigmob:
      +materialized: view
      +schema: br_rj_riodejaneiro_sigmob
