version: 2

models:
  # - name: data_versao_efetiva
  #   description: "Especifica qual data versao mais recente disponível para uma determinada data."
  #   columns:
  #     - name: data
  #       description: "The primary key for this table"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_agency
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_calendar
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_frota_determinada
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_holidays
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_linhas
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_routes
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_shapes
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_stop_details
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_stop_times
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_stops
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  #     - name: data_versao_efetiva_trips
  #       description: "data_versao mais recente para a tabela descrita no sufixo"
  #       tests:
  #         - not_null
  - name: trips_desaninhada
    description: Cadastro de itinerários (trips)
    columns:
      - name: trip_id
        description: Identificador único para um itinerário
        tests:
          - not_null
          - unique_by_date:
              date_column_name: data_versao
          - unique_relation:
              partition_column: data_versao
              relation_field: route_id
          - unique_relation:
              partition_column: data_versao
              relation_field: shape_id
      - name: shape_id
        description: Identificador único para uma linestring associada à um itinerário
        tests:
          - contained:
              in: ref("shapes_geom")
              field: shape_id
  - name: shapes_geom
    description: tabela com as linestrings de cada itinarário consolidadas a partir da captura ponto a ponto
    columns:
      - name: shape_id
        tests:
          - not_null
          - unique_by_date:
              date_column_name: data_versao
          - unique_relation:
              partition_column: data_versao
              relation_field: trip_id
          - contained:
              in: ref('trips_desaninhada')
              field: shape_id
