version: 2

models:
  - name: data_versao_efetiva
    description: "Especifica qual data versao mais recente disponível para uma determinada data."
    columns:
      - name: data
        description: "The primary key for this table"
        tests:
          - not_null
      - name: data_versao_efetiva_agency
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_calendar
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_frota_determinada
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_holidays
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_linhas
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_routes
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_shapes
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_stop_details
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_stop_times
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_stops
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
      - name: data_versao_efetiva_trips
        description: "data_versao mais recente para a tabela descrita no sufixo"
        tests:
          - not_null
